name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'AUTHORS.md'
      - 'CITATION.bib'
      - 'CONTRIBUTING.md'
      - 'LICENSE.md'
      - 'NEWS.md'
      - 'README.md'
      - '.github/workflows/CompatHelper.yml'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'AUTHORS.md'
      - 'CITATION.bib'
      - 'CONTRIBUTING.md'
      - 'LICENSE.md'
      - 'NEWS.md'
      - 'README.md'
      - '.github/workflows/CompatHelper.yml'
      - 'docs/**'
  workflow_dispatch:

# Cancel redundant CI tests automatically
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_unit_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        julia-version: ['1', '1.9']

    steps:
      - name: Check out project
        uses: actions/checkout@v4
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v1
      - name: Build package
        uses: julia-actions/julia-buildpkg@v1
      - name: Run unit tests
        uses: julia-actions/julia-runtest@v1
        with:
          annotate: true
          coverage: true
      - name: Process coverage results
        uses: julia-actions/julia-processcoverage@v1
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          fail_ci_if_error: true

  run_example_tests:
    needs: run_unit_tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        julia-version: ['1.0', '1.9']
    steps:
      - name: Check out project
        uses: actions/checkout@v4
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v1
      - name: Run example tests
        uses: julia-actions/julia-runtest@v1
        with:
          annotate: true
          coverage: false
